import Image from 'next/image';
import { getHomepageContent } from '@/lib/content/home';
import { Header, Footer } from '@/components/site-layout';
import { Counter } from '@/components/counter';
import { siteOrigin } from '@/lib/config';
export const dynamic = 'force-dynamic';
export const metadata = { alternates: siteOrigin() ? { canonical: '/' } : undefined };
const statusLabels = { open: 'เปิดรับสมัคร', nearly_full: 'ใกล้เต็ม', waitlist: 'Waiting List', closed: 'ยังไม่เปิดรับสมัคร' };
function dateLabel(value: string | null) { return value ? new Intl.DateTimeFormat('th-TH', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'Asia/Bangkok' }).format(new Date(value)) : 'รอประกาศวันเดินทาง'; }
function safeLine(value: string | null) { if (!value) return null; try { const url = new URL(value); return url.protocol === 'https:' && ['line.me', 'lin.ee'].includes(url.hostname) ? url.href : null; } catch { return null; } }
export default async function HomePage() {
  const content = await getHomepageContent();
  const { settings, programs, preparation, gallery, heroUrl, mode } = content;
  const line = safeLine(settings.lineUrl);
  const phone = settings.phone?.replace(/[\s()-]/g, '');
  return <><Header name={settings.siteName} /><main id="main">
    <section id="overview" className="hero wrap reveal" aria-labelledby="hero-title"><p className="eyebrow">A SUMMER BEYOND THE CLASSROOM / 中国</p><div className="hero-top"><h1 id="hero-title">{settings.headline}</h1><div className="hero-intro"><p>{settings.supportingText}</p><div className="actions"><a href="#programs" className="button">ดูโปรแกรม <span aria-hidden>↗</span></a><a href="#registration" className="button secondary">สมัครเลย</a></div></div></div>
      <div className="hero-art">{heroUrl ? <Image src={heroUrl} alt={settings.heroAlt || 'ภาพประกอบภูเขาและสถาปัตยกรรมจีน ใช้แทนภาพจริงชั่วคราว'} width={1600} height={660} sizes="(max-width: 600px) 100vw, 90vw" loading="eager" fetchPriority="high" /> : <div className="h-full flex items-center justify-center p-10 text-center">พื้นที่สำหรับภาพนักเรียนและสถาปัตยกรรมจีน<br />รอภาพที่ได้รับอนุญาตให้เผยแพร่</div>}</div><div className="art-caption"><span>ภาษา · วัฒนธรรม · มิตรภาพ · ประสบการณ์</span><span>{mode === 'demo' ? 'ภาพประกอบชั่วคราว / ไม่ใช่ภาพกิจกรรมจริง' : 'เรียนรู้โลกกว้าง ผ่านประสบการณ์ของคุณ'}</span></div>
      {mode === 'demo' && <p className="sample-note">เว็บไซต์ตัวอย่าง — โปรแกรมและสถิติเป็นข้อมูลสมมติสำหรับตรวจรูปแบบ ยังไม่เปิดรับสมัคร</p>}
      {mode === 'unconfigured' && <p className="sample-note">กำลังเตรียมข้อมูลโปรแกรมและรายละเอียดการเดินทาง โปรดกลับมาตรวจสอบอีกครั้ง</p>}
      {mode === 'unavailable' && <p className="sample-note" role="status">ยังโหลดข้อมูลล่าสุดไม่ได้ กรุณารีเฟรชหน้าเว็บหรือลองใหม่ภายหลัง</p>}
      <div className="stats"><p><span className="eyebrow">SMALL STEPS. BIG DISCOVERIES.</span><br />ทุกการเดินทาง คือจุดเริ่มต้น<br />ของการเติบโตครั้งใหม่</p><div className="stat"><strong>{settings.previousYearStudents === null ? '—' : <Counter value={settings.previousYearStudents} />}</strong><small>นักเรียนที่ร่วมเดินทาง{settings.previousYear ? ` ปี ${settings.previousYear}` : 'ในปีที่ผ่านมา'}{mode === 'demo' ? ' (ตัวอย่าง)' : ''}</small></div><div className="stat"><strong>学 · 行</strong><small>เรียนรู้ และออกไปสัมผัสด้วยตัวเอง</small></div></div>
    </section>
    <section id="programs" className="wrap section"><div className="section-head"><div><p className="eyebrow">01 / FIND YOUR SUMMER</p><h2>ซัมเมอร์แบบไหน…ที่เป็นคุณ</h2></div><p>ค้นพบภาษาและวัฒนธรรมในแบบของคุณ<br />เริ่มต้นจากประสบการณ์ที่อยากลอง</p></div>
      {programs.length ? <div className="program-grid">{programs.map((p, i) => <article key={p.id} className="program-card"><div className="program-image">{p.imageUrl ? <Image src={p.imageUrl} alt={p.cover_alt} width={800} height={450} sizes="(max-width: 600px) 100vw, 45vw" style={{ objectPosition: i ? 'right center' : 'left center' }} /> : <div className="p-8">รอภาพโปรแกรม</div>}</div><div className="program-meta"><span>{p.country} / {p.city}</span><span>{p.is_sample ? 'โปรแกรมตัวอย่าง' : statusLabels[p.registration_status]}</span></div><h3>{p.title}</h3><p>{p.summary}</p><div className="program-facts"><span>{p.age_min !== null && p.age_max !== null ? `อายุ ${p.age_min}–${p.age_max} ปี` : 'รอประกาศช่วงอายุ'}</span><span>{dateLabel(p.departure_date)}{p.return_date ? ` – ${dateLabel(p.return_date)}` : ''}</span></div><div className="program-foot"><span>{p.price === null ? 'รอประกาศราคา' : new Intl.NumberFormat('th-TH', { style: 'currency', currency: p.currency }).format(p.price)}</span><a href="#registration" className="underline underline-offset-4">การเปิดรับสมัคร ↗</a></div></article>)}</div> : <p className="empty">ยังไม่มีโปรแกรมที่เปิดเผยแพร่ โปรดกลับมาตรวจสอบอีกครั้ง</p>}
    </section>
    <section id="preparation" className="section preparation"><div className="wrap"><div className="section-head"><div><p className="eyebrow">02 / READY FOR THE JOURNEY</p><h2>ก้าวแรกที่มั่นใจ<br />ก่อนออกเดินทาง</h2></div><p>เตรียมพร้อมทีละขั้น เพื่อให้ทุกวันของซัมเมอร์<br />เต็มไปด้วยการเรียนรู้และความทรงจำ</p></div>{preparation.length ? <ol className="steps">{preparation.map((step, i) => <li key={step.id}><span aria-hidden>0{i + 1}</span><h3>{step.title}</h3><p>{step.description}</p></li>)}</ol> : <p>ทีมงานกำลังเตรียมคำแนะนำก่อนเดินทาง</p>}</div></section>
    <section id="gallery" className="wrap section"><div className="section-head"><div><p className="eyebrow">03 / MOMENTS THAT STAY</p><h2>เรื่องราวระหว่างทาง</h2></div><p>ช่วงเวลาของการเรียนรู้และมิตรภาพ<br />ที่อยากเก็บไว้ให้นานกว่าซัมเมอร์</p></div>{gallery.length ? <div className="gallery-grid">{gallery.map((g) => <figure key={g.id}>{g.imageUrl ? <Image src={g.imageUrl} alt={g.alt} width={600} height={500} sizes="(max-width: 600px) 100vw, 30vw" /> : <p className="empty">ยังโหลดภาพไม่ได้</p>}<figcaption>{g.caption} · {g.year}</figcaption></figure>)}</div> : <p className="empty">ภาพกิจกรรมกำลังอยู่ระหว่างเตรียมเผยแพร่ แล้วมาพบกับเรื่องราวจากการเดินทางไปด้วยกัน</p>}</section>
    <section id="registration" className="wrap"><div className="sample-note"><strong>การเปิดรับสมัคร</strong><p className="mb-0">ขณะนี้ยังไม่เปิดรับใบสมัครออนไลน์ รายละเอียดโปรแกรม เงื่อนไข และกำหนดการจะประกาศก่อนเปิดรับสมัคร</p></div></section>
    <section id="contact" className="wrap contact"><div><p className="eyebrow">LET’S PLAN YOUR NEXT CHAPTER</p><h2>เริ่มต้นวางแผนซัมเมอร์ของคุณ</h2><p className="muted">{settings.businessHours || 'ข้อมูลติดต่อและเวลาทำการจะประกาศเมื่อพร้อมให้บริการ'}</p></div><div className="actions">{line && <a className="button" href={line} rel="noopener noreferrer" target="_blank">พูดคุยทาง LINE ↗</a>}{phone && /^\+?[0-9]{8,15}$/.test(phone) && <a className="button secondary" href={`tel:${phone}`}>{settings.phone}</a>}{settings.email && <a className="button secondary" href={`mailto:${settings.email}`}>อีเมล</a>}{!line && !phone && !settings.email && <span className="legal-note">LINE · โทรศัพท์ · อีเมล — รอข้อมูลจริง</span>}</div></section>
  </main><Footer name={settings.siteName} address={settings.address} /></>;
}
