import Link from 'next/link';
import { PublicFrame, PageHero } from '@/components/public-frame';
import { getPublicContent } from '@/lib/content/public-source';
import { findProgram } from '@/lib/content/public';
import { publicMetadata } from '@/lib/public-metadata';
export const metadata = publicMetadata('เตรียมข้อมูลก่อนสมัคร', 'ทบทวนโปรแกรมที่สนใจและข้อมูลที่ต้องเตรียมร่วมกับผู้ปกครองก่อนเปิดรับสมัคร', '/apply');
export default async function ApplyPage({ searchParams }: { searchParams: Promise<{ program?: string | string[] }> }) {
  const query = (await searchParams).program;
  const selected = findProgram(getPublicContent().programs, query);
  return <PublicFrame><main id="main"><PageHero number="05" title="ก้าวต่อไปของซัมเมอร์คุณ" english="Your next chapter." description="เตรียมความพร้อมร่วมกับครอบครัว ก่อนเริ่มต้นการสมัครเมื่อโปรแกรมเปิดรับอย่างเป็นทางการ" /><div className="edition-wrap"><section className="public-section public-two-column"><div><h2>โปรแกรมที่สนใจ</h2></div><div>{selected ? <><h3>{selected.title}</h3><p>ข้อมูลตัวอย่าง · อายุ {selected.ageMin}–{selected.ageMax} ปี · {selected.durationDays} วัน</p><Link className="edition-text-link" href={`/programs/${selected.slug}`}>ทบทวนรายละเอียดโปรแกรม ↗</Link></> : <p>{query ? 'ไม่พบโปรแกรมที่เลือก กรุณากลับไปเลือกโปรแกรมอีกครั้ง' : 'ยังไม่ได้เลือกโปรแกรม คุณสามารถสำรวจเส้นทางที่สนใจก่อนได้'}</p>}<p className="public-demo-note">ยังไม่เปิดรับใบสมัครออนไลน์ หน้านี้ใช้เตรียมความพร้อมเท่านั้น ไม่มีการกรอก บันทึก หรือส่งข้อมูลส่วนบุคคล</p></div></section><section className="public-section public-two-column"><div><p className="edition-kicker">01 / GET READY</p><h2>ข้อมูลที่ควรเตรียม</h2></div><ul className="public-list"><li>ข้อมูลนักเรียนและเอกสารระบุตัวตนที่ตรงกัน</li><li>ข้อมูลผู้ปกครองและช่องทางติดต่อที่ตรวจสอบได้</li><li>โปรแกรมที่สนใจและความพร้อมในการเดินทาง</li><li>คำถามเกี่ยวกับการดูแล สุขภาพ และการช่วยเหลือที่ควรหารือเป็นการส่วนตัวกับทีมงาน</li></ul></section><section className="public-section public-two-column"><div><p className="edition-kicker">02 / READ TOGETHER</p><h2>ก่อนส่งใบสมัครจริง</h2></div><div><p>เมื่อระบบเปิดรับสมัคร ผู้สมัครจะต้องอ่านและยอมรับ Terms &amp; Conditions ฉบับที่ประกาศก่อนส่งใบสมัคร</p><p>ผู้เยาว์ต้องได้รับความยินยอมจากผู้ปกครอง โปรดทบทวนโปรแกรม เงื่อนไข และรายละเอียดการดูแลร่วมกัน</p><p>หน้านี้ยังไม่มีการยอมรับเงื่อนไขหรือเก็บความยินยอม</p></div></section><div className="public-cta actions"><Link className="button" href="/programs">กลับไปเลือกโปรแกรม ↗</Link><Link className="edition-text-link" href="/contact">ช่องทางติดต่อ →</Link></div></div></main></PublicFrame>;
}
